CSharpMVC/SlnRevisaoCSharpMVC/src/Devs2Blu.ProjetosAula.CSharpMVCRevisao/Models/DTOAPI/CardDTO.cs
namespace Devs2Blu.ProjetosAula.CSharpMVCRevisao.Models.DTOAPI
{
    public class CardDTO
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Desc { get; set; }
        public List<CardImagesDTO> Card_Images { get; set; }
    }
}

CSharpMVC/SlnRevisaoCSharpMVC/src/Devs2Blu.ProjetosAula.CSharpMVCRevisao/Models/DTOAPI/CardImagesDTO.cs
namespace Devs2Blu.ProjetosAula.CSharpMVCRevisao.Models.DTOAPI
{
    public class CardImagesDTO
    {
        public int Id { get; set; }
        public string Image_Url { get; set; }
        public string Image_Url_Small { get; set; }
    }
}

CSharpMVC/SlnRevisaoCSharpMVC/src/Devs2Blu.ProjetosAula.CSharpMVCRevisao/Models/DTOAPI/GetListDataCardsDTO.cs
namespace Devs2Blu.ProjetosAula.CSharpMVCRevisao.Models.DTOAPI
{
    public class GetListDataCardsDTO
    {
        public List<CardDTO> Data { get; set; }
    }
}

CSharpMVC/SlnRevisaoCSharpMVC/src/Devs2Blu.ProjetosAula.CSharpMVCRevisao/Models/ErrorViewModel.cs
namespace Devs2Blu.ProjetosAula.CSharpMVCRevisao.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CSharpMVC/SlnRevisaoCSharpMVC/src/Devs2Blu.ProjetosAula.CSharpMVCRevisao/Controllers/CardApiController.cs
using Devs2Blu.ProjetosAula.CSharpMVCRevisao.Models;
using Devs2Blu.ProjetosAula.CSharpMVCRevisao.Models.DTOAPI;
using Devs2Blu.ProjetosAula.CSharpMVCRevisao.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Devs2Blu.ProjetosAula.CSharpMVCRevisao.Controllers
{
    [Route("cards")]
    public class CardApiController : Controller
    {
        private readonly ILogger<CardApiController> _logger;
        private readonly ServiceAPI service;

        public CardApiController(ILogger<CardApiController> logger)
        {
            _logger = logger;
            service = new ServiceAPI();
        }

        [Route("")]
        [Route("index")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("loadcards")]
        public async Task<PartialViewResult> LoadListCards()
        {
            _logger.LogInformation("Carregando a lista de Cards");
            var result = await service.GetListCards();
            var listCards = result.Take(20).ToList();
            return PartialView(listCards);
        }

        [Route("search/{nameCard}")]
        public async Task<PartialViewResult> SearchCard(string nameCard)
        {
            var card = await service.GetCardByName(nameCard);            
            return PartialView(card);
        }

    }
}

CSharpMVC/SlnRevisaoCSharpMVC/src/Devs2Blu.ProjetosAula.CSharpMVCRevisao/Controllers/HomeController.cs
using Devs2Blu.ProjetosAula.CSharpMVCRevisao.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Devs2Blu.ProjetosAula.CSharpMVCRevisao.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CSharpMVC/SlnRevisaoCSharpMVC/src/Devs2Blu.ProjetosAula.CSharpMVCRevisao/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="content-list" class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CSharpMVC/SlnRevisaoCSharpMVC/src/Devs2Blu.ProjetosAula.CSharpMVCRevisao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Devs2Blu.ProjetosAula.CSharpMVCRevisao</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Devs2Blu.ProjetosAula.CSharpMVCRevisao.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="mb-3">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-danger border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCRevisao</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CardApi" asp-action="Index">Lista de Cards</a>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input id="input-search" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button id="btn-search" class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Devs2Blu.ProjetosAula.CSharpMVCRevisao - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/scripts.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>